#+TITLE: Config
#+PROPERTY: header-args :tangle config :comments both :padline no

* Variables
Set variables that will be used through out the config
- Set modifier key to mod4
#+begin_src conf
set $mod mod4
#+end_src
- Map h, j, k, and l to left, down, up and right variables
#+begin_src conf
set $left h
set $down j
set $up k
set $right l
#+end_src
- Variables for various programs
#+begin_src conf
set $term kitty
set $menu wofi --show drun
set $wallpaper /home/arijit/Downloads/wallpaper.jpg
#+end_src

* Output Configuration
This is for any configuration related to display like multi-monitors, wallpapers, swayidle etc
#+begin_src conf
output * bg $wallpaper fill
#+end_src
* Key Bindings
Maps the various key bindings
** Application Launching
#+begin_src conf
# Start a terminal
bindsym $mod+Return exec $term
# Kill focused window
bindsym $mod+q kill
# Start run launcher
bindsym $mod+r exec $menu
# Start emacsclient
bindsym $mod+e exec emacsclient -c -n
# Screenshot using grim
bindsym F11 exec grim
#+end_src
** Floating
The =floating_modifier= declares the key to switch to floating mode operation like resizing and moving.
This is set to the $mod key. A =normal=/=inverse= is also passed to set the mouse configration to use
- =normal= means to use the left mouse button for moving windows and right button for resizing
- =inverse= menas to use the right mouse button for moving windows and left button for resize

The =$mod+Shift+space= will toggle between tiling and floating mode for the currently focused window
while =$mod+space= toggles between tiling and floating mode for the current workspace

#+begin_src conf
floating_modifier $mod normal
# Toggle the current focus between tiling and floating mode
bindsym $mod+Shift+space floating toggle

# Swap focus between the tiling area and the floating area
bindsym $mod+space focus mode_toggle
#+end_src
** Layout
#+begin_src conf
# You can "split" the current object of your focus with
# $mod+b or $mod+v, for horizontal and vertical splits
# respectively.
bindsym $mod+b splith
bindsym $mod+v splitv

# Switch the current container between different layout styles
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+shift+e layout toggle split

# Make the current focus fullscreen
bindsym $mod+f fullscreen

# Move focus to the parent container
bindsym $mod+a focus parent
#+end_src
** Session
#+begin_src conf
# Reload sway
bindsym $mod+Control+r reload
# Exit sway (logs you out of your Wayland session)
bindsym $mod+Control+q exec wlogout
#+end_src
** Scratchpad
Sway has a "scratchpad", which is a bag of holding for windows.
You can send windows there and get them back later.
#+begin_src conf
    # Move the currently focused window to the scratchpad
    bindsym $mod+Shift+minus move scratchpad

    # Show the next scratchpad window or hide the focused scratchpad window.
    # If there are multiple scratchpad windows, this command cycles through them.
    bindsym $mod+minus scratchpad show
#+end_src

** Window Movement
#+begin_src conf
# Move your focus around
bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right
# Or use $mod+[up|down|left|right]
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
#+end_src
** Window Management
#+begin_src conf
# Move the focused window with the same, but add Shift
bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right
# Ditto, with arrow keys
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right
#+end_src

** Workspaces
*** Switching
#+begin_src conf
bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+5 workspace number 5
bindsym $mod+6 workspace number 6
bindsym $mod+7 workspace number 7
bindsym $mod+8 workspace number 8
bindsym $mod+9 workspace number 9
bindsym $mod+0 workspace number 10
#+end_src
*** Window Shifting
#+begin_src conf
bindsym $mod+Shift+1 move container to workspace number 1
bindsym $mod+Shift+2 move container to workspace number 2
bindsym $mod+Shift+3 move container to workspace number 3
bindsym $mod+Shift+4 move container to workspace number 4
bindsym $mod+Shift+5 move container to workspace number 5
bindsym $mod+Shift+6 move container to workspace number 6
bindsym $mod+Shift+7 move container to workspace number 7
bindsym $mod+Shift+8 move container to workspace number 8
bindsym $mod+Shift+9 move container to workspace number 9
bindsym $mod+Shift+0 move container to workspace number 10
#+end_src

** Mode Switching
#+begin_src conf
bindsym $mod+Shift+r mode "resize"
#+end_src
* Modes
** resize
#+begin_src conf
mode "resize" {
# left will shrink the containers width
# right will grow the containers width
# up will shrink the containers height
# down will grow the containers height
bindsym $left resize shrink width 10px
bindsym $down resize grow height 10px
bindsym $up resize shrink height 10px
bindsym $right resize grow width 10px

# Ditto, with arrow keys
bindsym Left resize shrink width 10px
bindsym Down resize grow height 10px
bindsym Up resize shrink height 10px
bindsym Right resize grow width 10px

# Return to default mode
bindsym Return mode "default"
bindsym Escape mode "default"
}
#+end_src
* Autostart
#+begin_src conf
# Status Bar:and network manager
exec waybar &
# exec nm-applet --indicator &
# exec syncthing serve --no-browser &
# exec emacs daemon
exec emacs --daemon &
#+end_src

** GTK Config
#+begin_src conf
set $gnome-schema org.gnome.desktop.interface

exec_always {
    export GTK_THEME='Adapta-Nokto-Eta'
    gsettings set $gnome-schema gtk-theme 'Adapta-Nokto-Eta'
    gsettings set $gnome-schema icon-theme 'Tela-Dark'
    gsettings set $gnome-schema cursor-theme 'DMZ'
}
#+end_src
* Additional Configuration
#+begin_src conf
# hide titlebars and add gaps
default_border pixel 2
gaps outer 3
gaps inner 5
#+end_src
* Default Import (DO NOT MODIFY)
*Don't forget to include the default sway configration*
#+begin_src conf
include /etc/sway/config.d/*
#+end_src
