vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.background = "dark"
vim.opt.laststatus = 3
vim.opt.cmdheight = 0
vim.opt.clipboard = "unnamedplus"
vim.g.mapleader = " "
vim.opt.termguicolors = true
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.cursorline = true
vim.opt.cursorlineopt = "number"
vim.g.zig_fmt_autosave = 0
