[colors]
background = "#11121d"
foreground = "#a0a8cd"
selection_bg = '#212234'
cursor_bg = "#a0a8cd"
split = "#282c34"

ansi = [
  "#06080a", # black
  "#ee6d85", # red
  "#95c561", # green
  "#d7a65f", # yellow
  "#7199ee", # blue
  "#a485dd", # magenta
  "#38a89d", # cyan
  "#a0a8cd"  # white
]

brights = [
  "#212234", # black
  "#ee6d85", # red
  "#95c561", # green
  "#d7a65f", # yellow
  "#7199ee", # blue
  "#a485dd", # magenta
  "#38a89d", # cyan
  "#a0a8cd"  # white
]
