import = ["/home/arijit/.config/alacritty/theme.toml"]

[cursor]
style = "Block"

[font]
size = 10.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[window]
opacity = 0.8
startup_mode = "Windowed"
title = "Alacritty"
