[cursor]
style = "Block"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[window]
opacity = 0.8
startup_mode = "Windowed"
title = "Alacritty"

[general]
import = ["/home/arijit/.config/alacritty/theme.toml"]
